version: "3.9"

services:
  localstack:
    image: localstack/localstack:stable
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEBUG=0
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  auto-plot:
    image: ${AUTO_PLOT_IMAGE_NAME}
    container_name: auto-plot
    environment:
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}
      - STORAGE_PREFIX=${REMOTE_STORAGE_PREFIX}
      - STORAGE_BASE=${REMOTE_STORAGE_BASE}
    ports:
      - "8080:8080"
    volumes:
      - "${HOST_STORAGE_PREFIX}${HOST_STORAGE_BASE}:${AUTO_PLOT_STORAGE_PREFIX}${AUTO_PLOT_STORAGE_BASE}"
    depends_on:
      - localstack

  plot-generation:
    image: ${IMAGE_NAME}
    container_name: plot-generation
    environment:
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}
      - STORAGE_PREFIX=${REMOTE_STORAGE_PREFIX}
      - CONTAINER_STORAGE_PREFIX=${CONTAINER_STORAGE_PREFIX}
      - STORAGE_BASE=${REMOTE_STORAGE_BASE}
      - CONTAINER_STORAGE_BASE=${CONTAINER_STORAGE_BASE}
      - AUTO_PLOT_URL_BASE=${AUTO_PLOT_URL_BASE}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "${HOST_STORAGE_PREFIX}${HOST_STORAGE_BASE}:${CONTAINER_STORAGE_PREFIX}${CONTAINER_STORAGE_BASE}"
    depends_on:
      - auto-plot
      - localstack
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
